service: backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: travel 
          method: get 
  createRequest:
    handler: handler.createRequest
    environment:
      REQUEST_TABLE : !Ref RequestTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt RequestTable.Arn
    events:
      - http:
          path: travel 
          method: post 
plugins:
  - serverless-iam-roles-per-function

resources:
 Resources:
  RequestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RequestTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: requestId 
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
